/* prettier-ignore-start */

/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file is auto-generated by TanStack Router

import { createFileRoute } from '@tanstack/react-router'

// Import Routes

import { Route as rootRoute } from './routes/__root'
import { Route as CreateTripIndexImport } from './routes/create-trip/index'
import { Route as TripsIdImport } from './routes/trips/$id'

// Create Virtual Routes

const IndexLazyImport = createFileRoute('/')()

// Create/Update Routes

const IndexLazyRoute = IndexLazyImport.update({
  path: '/',
  getParentRoute: () => rootRoute,
} as any).lazy(() => import('./routes/index.lazy').then((d) => d.Route))

const CreateTripIndexRoute = CreateTripIndexImport.update({
  path: '/create-trip/',
  getParentRoute: () => rootRoute,
} as any)

const TripsIdRoute = TripsIdImport.update({
  path: '/trips/$id',
  getParentRoute: () => rootRoute,
} as any)

// Populate the FileRoutesByPath interface

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexLazyImport
      parentRoute: typeof rootRoute
    }
    '/trips/$id': {
      id: '/trips/$id'
      path: '/trips/$id'
      fullPath: '/trips/$id'
      preLoaderRoute: typeof TripsIdImport
      parentRoute: typeof rootRoute
    }
    '/create-trip/': {
      id: '/create-trip/'
      path: '/create-trip'
      fullPath: '/create-trip'
      preLoaderRoute: typeof CreateTripIndexImport
      parentRoute: typeof rootRoute
    }
  }
}

// Create and export the route tree

export const routeTree = rootRoute.addChildren({
  IndexLazyRoute,
  TripsIdRoute,
  CreateTripIndexRoute,
})

/* prettier-ignore-end */

/* ROUTE_MANIFEST_START
{
  "routes": {
    "__root__": {
      "filePath": "__root.tsx",
      "children": [
        "/",
        "/trips/$id",
        "/create-trip/"
      ]
    },
    "/": {
      "filePath": "index.lazy.tsx"
    },
    "/trips/$id": {
      "filePath": "trips/$id.tsx"
    },
    "/create-trip/": {
      "filePath": "create-trip/index.tsx"
    }
  }
}
ROUTE_MANIFEST_END */
